import './scss/main.scss'
import './js/preloader.js'
import { initDecryptedText } from './js/decrypted-text.js'
import './js/cursor.js'
document.addEventListener('DOMContentLoaded', initDecryptedText)
import './js/sphere.js'
import './js/my-story.js'
import './js/theme.js'
import './js/reveal.js'
// import './js/dither.js'
import './js/popup.js'
import './js/projects.js'
import './js/proj-modal.js'
import './js/contact-socials.js'
import './js/nav.js'
import './js/section-transitions.js'